import { readFile } from "fs/promises";
import mongoose from "mongoose";
import dotenv from "dotenv";
dotenv.config();

import Job from "./models/jobModel.js";
import User from "./models/UserModel.js";
import { create } from "domain";

try {
  await mongoose.connect(process.env.MONGO_URL);
  const user = await User.findOne({ email: "test@test.com" });
  const jsonJobs = JSON.parse(
    await readFile(new URL("./utils/mockData.json", import.meta.url))
  );
  const jobs = jsonJobs.map((job) => {
    return { ...job, createdBy: user._id };
  });
  
  await Job.deleteMany({ createdBy: user._id });
  await Job.create(jobs);
  console.log("Success!!");
  process.exit(0);
} catch (error) {
  console.log(error);
  process.exit(1);
}

// use 'node populate' to run this
// why we use this - it is to create mock data for a user
// mockData.json file is generated by https://www.mockaroo.com/